import React, { useEffect, useState } from "react";
import { Pencil, Plus, X } from "lucide-react";
import { api } from "../api/client.js";
import { DataTable } from "../components/DataTable.jsx";

const emptyBatch = { name: "", course: "", faculty: "", timing: "", startDate: "", endDate: "", status: "Upcoming" };
const idOf = (value) => value?._id || value || "";

export function BatchManagementPage() {
  const [batches, setBatches] = useState([]); const [courses, setCourses] = useState([]); const [faculty, setFaculty] = useState([]);
  const [form, setForm] = useState(emptyBatch); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { const [batchData, courseData, userData] = await Promise.all([api("/batches?limit=100"), api("/courses?limit=100"), api("/users?limit=100")]); setBatches(batchData.items || []); setCourses(courseData.items || []); setFaculty((userData.items || []).filter((user) => user.role === "Faculty")); };
  useEffect(() => { load().catch((error) => setMessage(error.message)); }, []);
  const showCreate = () => { setEditing(null); setForm({ ...emptyBatch, course: courses.find((item) => item.isActive !== false)?._id || "" }); setOpen(true); setMessage(""); };
  const showEdit = (batch) => { setEditing(batch); setForm({ name: batch.name || "", course: idOf(batch.course), faculty: idOf(batch.faculty), timing: batch.timing || "", startDate: batch.startDate?.slice(0, 10) || "", endDate: batch.endDate?.slice(0, 10) || "", status: batch.status || "Upcoming" }); setOpen(true); setMessage(""); };
  const submit = async (event) => { event.preventDefault(); try { const payload = { ...form, faculty: form.faculty || null }; await api(editing ? `/batches/${editing._id}` : "/batches", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); setOpen(false); setMessage(editing ? "Batch updated successfully" : "Batch created successfully"); await load(); } catch (error) { setMessage(error.message); } };
  const courseName = (id) => courses.find((item) => item._id === idOf(id))?.name || "-"; const facultyName = (id) => faculty.find((item) => item._id === idOf(id))?.name || "Not assigned";
  const columns = [{ key: "name", label: "Batch Name" }, { key: "course", label: "Course", render: (row) => courseName(row.course) }, { key: "faculty", label: "Faculty", render: (row) => facultyName(row.faculty) }, { key: "timing", label: "Timing" }, { key: "status", label: "Status" }, { key: "actions", label: "Actions", render: (row) => <button onClick={() => showEdit(row)} className="rounded-md border border-slate-200 p-2 text-[#ea580c] hover:bg-[#fff3e8]"><Pencil size={16} /></button> }];
  return <div className="space-y-5"><section className="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-5 shadow-sm md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold">Batches</h2><p className="text-sm text-slate-500">Connect a course, faculty, schedule and dates to each batch.</p></div><button onClick={showCreate} className="inline-flex items-center justify-center gap-2 rounded-md bg-[#f97316] px-4 py-2 text-sm font-semibold text-white hover:bg-[#111315]"><Plus size={17} /> New Batch</button></section>{message && <p className="rounded-md border border-[#f97316]/20 bg-[#fff3e8] px-4 py-3 text-sm font-semibold text-[#c2410c]">{message}</p>}<DataTable columns={columns} rows={batches} />
    {open && <Modal title={editing ? "Edit Batch" : "New Batch"} onClose={() => setOpen(false)}><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><Field label="Batch Name"><input required className={inputClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Course"><select required className={inputClass} value={form.course} onChange={(e) => setForm({ ...form, course: e.target.value })}><option value="">Select course</option>{courses.filter((item) => item.isActive !== false).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></Field><Field label="Faculty"><select className={inputClass} value={form.faculty} onChange={(e) => setForm({ ...form, faculty: e.target.value })}><option value="">Not assigned</option>{faculty.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></Field><Field label="Timing"><input required placeholder="e.g. 10:00 AM - 12:00 PM" className={inputClass} value={form.timing} onChange={(e) => setForm({ ...form, timing: e.target.value })} /></Field><Field label="Start Date"><input required type="date" className={inputClass} value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /></Field><Field label="End Date"><input required type="date" min={form.startDate} className={inputClass} value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></Field><Field label="Status"><select className={inputClass} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{["Upcoming", "Running", "Completed", "Cancelled"].map((status) => <option key={status}>{status}</option>)}</select></Field><div className="flex items-end justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-md border border-slate-200 px-4 py-2 text-sm font-semibold">Cancel</button><button className="rounded-md bg-[#f97316] px-4 py-2 text-sm font-semibold text-white hover:bg-[#111315]">{editing ? "Update Batch" : "Create Batch"}</button></div></form></Modal>}
  </div>;
}
const inputClass = "mt-1.5 w-full rounded-md border border-slate-300 px-3 py-2 outline-none focus:border-[#f97316]";
function Field({ label, children }) { return <label className="block text-sm font-semibold">{label}{children}</label>; }
function Modal({ title, onClose, children }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-2xl rounded-lg bg-white p-5 shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={onClose} className="rounded-md p-2 hover:bg-slate-100"><X size={18} /></button></div>{children}</div></div>; }
