import React, { useEffect, useState } from "react";
import { Award, BookOpen, BriefcaseBusiness, Check, ChevronDown, ChevronUp, Clock3, Code2, Download, ExternalLink, FileText, GraduationCap, Layers3, MessageCircle, Phone, Rocket, Sparkles, Users } from "lucide-react";
import { Footer, navigateTo } from "../components/PublicLayout.jsx";
import { findCourseDetail, courseDetails } from "../data/courseDetails.js";

const iconList = [GraduationCap, BookOpen, Users, BriefcaseBusiness, FileText, Award, MessageCircle, Layers3, Rocket, Sparkles];
const titleClass = "text-2xl font-black tracking-tight sm:text-3xl";

function Action({ children, secondary = false, onClick }) { return <button onClick={onClick} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-5 text-sm font-bold transition ${secondary ? "border border-white/25 bg-white/10 text-white hover:bg-white/20" : "bg-[#f97316] text-white shadow-lg shadow-orange-900/30 hover:bg-[#ea580c]"}`}>{children}</button>; }
function Section({ eyebrow, title, children, className = "" }) { return <section className={`mx-auto max-w-7xl px-4 py-10 sm:px-6 md:py-14 lg:px-8 ${className}`}><p className="text-xs font-black uppercase tracking-[.18em] text-[#ea580c]">{eyebrow}</p><h2 className={`mt-2 ${titleClass}`}>{title}</h2>{children}</section>; }

export function CourseDetailPage({ slug }) {
  const course = findCourseDetail(slug);
  const [openModule, setOpenModule] = useState(0);
  const [faq, setFaq] = useState(null);
  useEffect(() => {
    if (!course) return;
    document.title = `${course.name} | Coding Wallah`;
    const script = document.createElement("script"); script.type = "application/ld+json"; script.text = JSON.stringify({ "@context": "https://schema.org", "@type": "Course", name: course.name, description: course.overview, provider: { "@type": "Organization", name: "Coding Wallah" }, educationalLevel: course.level }); document.head.appendChild(script);
    return () => script.remove();
  }, [course]);
  if (!course) return <main className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="text-3xl font-black">Course not found</h1><button onClick={() => navigateTo("/courses")} className="mt-5 font-bold text-orange-600">Back to courses</button></main>;
  const contact = () => navigateTo(`/contact?course=${encodeURIComponent(course.name)}`);
  return <>
    <main>
      <nav aria-label="Breadcrumb" className="mx-auto max-w-7xl px-4 pt-5 text-sm text-slate-500 sm:px-6 lg:px-8"><button onClick={() => navigateTo("/")} className="hover:text-orange-600">Home</button> <span className="mx-2">/</span><button onClick={() => navigateTo("/courses")} className="hover:text-orange-600">Courses</button><span className="mx-2">/</span><span className="text-slate-700 dark:text-slate-200">{course.name}</span></nav>
      <section className="mx-auto mt-4 max-w-7xl overflow-hidden rounded-3xl bg-[#111315] px-6 py-10 text-white shadow-2xl sm:px-10 md:py-14 lg:px-14">
        <div className="grid items-center gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><p className="inline-flex rounded-full border border-orange-300/30 bg-orange-400/10 px-3 py-1 text-xs font-bold text-orange-200">Career-focused programme</p><h1 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">{course.name}</h1><p className="mt-4 text-xl font-bold text-orange-200">{course.tag}</p><p className="mt-4 max-w-2xl leading-7 text-slate-300">{course.overview}</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{[["Duration", course.duration], ["Level", course.level], ["Mode", course.mode], ["Certification", "Included"]].map(([a,b]) => <div key={a} className="rounded-xl border border-white/10 bg-white/5 p-3"><span className="block text-xs text-slate-400">{a}</span><strong className="mt-1 block">{b}</strong></div>)}</div><div className="mt-7 flex flex-wrap gap-3"><Action onClick={contact}>Enroll now <Rocket size={16}/></Action><Action secondary onClick={() => window.print()}><Download size={16}/> Download brochure</Action></div></div><img src={course.image} alt="" className="h-64 w-full rounded-2xl object-cover opacity-90 shadow-xl lg:h-[360px]" /></div>
      </section>
      <Section eyebrow="The programme" title="Learn by building work employers can inspect."><div className="grid gap-8 lg:grid-cols-[1fr_330px]"><div className="space-y-4 text-[15px] leading-7 text-slate-600 dark:text-slate-300"><p>{course.about}</p></div><aside className="rounded-2xl border border-orange-100 bg-orange-50 p-5 dark:border-orange-400/20 dark:bg-orange-400/10"><h3 className="font-black">Career snapshot</h3><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-slate-500">Potential roles</dt><dd className="font-bold">{course.roles.join(" · ")}</dd></div><div><dt className="text-slate-500">Indicative salary</dt><dd className="font-bold">{course.salary}</dd></div><div><dt className="text-slate-500">Hiring spaces</dt><dd className="font-bold">{course.companies}</dd></div></dl></aside></div></Section>
      <Section eyebrow="What makes it different" title="Everything needed to keep moving forward." className="bg-white/60 dark:bg-white/[.02]"><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{course.highlights.map((item, i) => { const Icon = iconList[i % iconList.length]; return <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-white/5"><Icon size={20} className="text-orange-500"/><span className="text-sm font-bold">{item}</span></div>; })}</div></Section>
      <Section eyebrow="Learning roadmap" title="A structured path from foundations to portfolio."><div className="mt-7 grid gap-3">{course.modules.map((module, i) => <article key={module.title} className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-white/10 dark:bg-white/5"><button onClick={() => setOpenModule(openModule === i ? -1 : i)} className="flex w-full items-center justify-between gap-4 p-5 text-left"><span><b className="mr-3 text-orange-600">{String(i+1).padStart(2,"0")}</b><strong>{module.title.replace(/^Module \d+: /, "")}</strong></span>{openModule === i ? <ChevronUp/> : <ChevronDown/>}</button>{openModule === i && <div className="grid gap-3 border-t border-slate-100 p-5 text-sm dark:border-white/10 sm:grid-cols-2"><p><b>Topics:</b> {module.topics}</p><p><b>Mini project:</b> {module.miniProject}</p><p><b>Assignment:</b> {module.assignment}</p><p><b>Interview practice:</b> {module.interview}</p></div>}</article>)}</div></Section>
      <Section eyebrow="Toolbox" title="Modern tools, taught in context."><div className="mt-7 flex flex-wrap gap-3">{course.tools.map((tool) => <span key={tool} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold shadow-sm dark:border-white/10 dark:bg-white/5">{tool}</span>)}</div></Section>
      <Section eyebrow="Generative AI in this course" title="Use AI to accelerate thoughtful work—not skip the thinking." className="bg-gradient-to-br from-slate-950 to-slate-800 text-white"><p className="mt-4 max-w-3xl leading-7 text-slate-300">You practise AI-assisted planning, code or analysis generation, debugging, documentation, test creation and automation. Each workflow includes prompt design, validation, privacy awareness and a human review step so you can explain and own the final result.</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{course.aiTools.map((tool) => <div key={tool} className="rounded-xl border border-white/10 bg-white/5 p-4 text-sm font-bold">{tool}<span className="mt-2 block text-xs font-normal text-slate-400">Hands-on workflow lab</span></div>)}</div></Section>
      <Section eyebrow="Portfolio work" title="Projects with a clear story and outcome."><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{course.projects.map((p) => <article key={p.name} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/5"><span className="text-xs font-black uppercase text-orange-600">{p.difficulty}</span><h3 className="mt-2 font-black">{p.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{p.description}</p><p className="mt-3 text-xs font-bold text-slate-500">{p.technologies}</p></article>)}</div></Section>
      <Section eyebrow="Capstone & career" title="Finish with work you can present."><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{course.capstones.map((p) => <article key={p.name} className="rounded-2xl bg-[#fff3e8] p-5 dark:bg-orange-400/10"><h3 className="font-black">{p.name}</h3><p className="mt-2 text-sm">Architecture, stack, modules, deployment and presentation review included.</p></article>)}<article className="rounded-2xl border border-slate-200 p-5 dark:border-white/10"><h3 className="font-black">Placement programme</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Resume and LinkedIn refinement, GitHub portfolio, aptitude practice, technical and HR mock interviews, company referrals and guided applications.</p></article></div></Section>
      <Section eyebrow="Your outcome" title="What you will be ready to do."><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{course.outcomes.map((o) => <p key={o} className="flex gap-2 text-sm"><Check size={18} className="shrink-0 text-emerald-600"/>{o}</p>)}</div></Section>
      <Section eyebrow="Common questions" title="Answers before you begin." className="bg-white/60 dark:bg-white/[.02]"><div className="mt-7 grid gap-3">{course.faqs.map((item, i) => <article key={item.q} className="rounded-xl border border-slate-200 bg-white dark:border-white/10 dark:bg-white/5"><button onClick={() => setFaq(faq === i ? null : i)} className="flex w-full items-center justify-between gap-4 p-5 text-left text-sm font-bold">{item.q}{faq === i ? <ChevronUp size={18}/> : <ChevronDown size={18}/>}</button>{faq === i && <p className="border-t border-slate-100 p-5 text-sm leading-6 text-slate-600 dark:border-white/10 dark:text-slate-300">{item.a}</p>}</article>)}</div></Section>
      <section className="mx-auto mb-12 max-w-7xl rounded-3xl bg-orange-500 px-6 py-10 text-center text-white sm:px-10"><p className="text-sm font-bold uppercase tracking-widest text-orange-100">Your next chapter starts here</p><h2 className="mt-3 text-3xl font-black">Ready to start your career?</h2><p className="mx-auto mt-3 max-w-xl text-orange-50">Talk to a counsellor about batches, fees, eligibility and the right learning path.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Action onClick={contact}>Enroll now</Action><button onClick={contact} className="rounded-xl border border-white/50 px-5 py-3 text-sm font-bold"><MessageCircle size={16} className="mr-2 inline"/> WhatsApp</button><button onClick={contact} className="rounded-xl border border-white/50 px-5 py-3 text-sm font-bold"><Phone size={16} className="mr-2 inline"/> Call now</button></div></section>
    </main><Footer />
  </>;
}
