import React, { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Trash2, UserCheck, X } from "lucide-react";
import { api } from "../api/client.js";
import { MetricCard, formatDate } from "../student/components/StudentUI.jsx";

const tabs = ["Executives", "Leads", "Follow-ups", "Tasks"];
const emptyUser = { name: "", email: "", mobile: "", password: "", isActive: true };
const emptyTask = { title: "", description: "", dueDate: "", priority: "Medium", assignedTo: "" };

export function DigitalMarketingManagementPage() {
  const [tab, setTab] = useState("Executives"); const [executives, setExecutives] = useState([]); const [leads, setLeads] = useState([]); const [followUps, setFollowUps] = useState([]); const [tasks, setTasks] = useState([]);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [message, setMessage] = useState(""); const [userModal, setUserModal] = useState(false); const [editing, setEditing] = useState(null); const [userForm, setUserForm] = useState(emptyUser); const [taskModal, setTaskModal] = useState(false); const [taskForm, setTaskForm] = useState(emptyTask);
  const load = async () => { const [u, l, f, t] = await Promise.all([api("/digital-marketing/admin/executives"), api("/digital-marketing/admin/leads"), api("/digital-marketing/admin/follow-ups"), api("/digital-marketing/admin/tasks")]); setExecutives(u.items || []); setLeads(l.items || []); setFollowUps(f.items || []); setTasks(t.items || []); };
  useEffect(() => { load().catch((e) => setMessage(e.message)); }, []);
  const activeExecutives = executives.filter((item) => item.isActive);
  const totals = { leads: executives.reduce((n, x) => n + x.leadCount, 0), converted: executives.reduce((n, x) => n + x.convertedLeads, 0), followUps: executives.reduce((n, x) => n + x.pendingFollowUps, 0), tasks: executives.reduce((n, x) => n + x.taskCount, 0) };
  const matches = (values) => !search || values.some((value) => String(value || "").toLowerCase().includes(search.toLowerCase()));
  const filteredExecutives = useMemo(() => executives.filter((x) => (!status || (status === "Active" ? x.isActive : !x.isActive)) && matches([x.name, x.email, x.mobile])), [executives, search, status]);
  const filteredLeads = leads.filter((x) => (!status || x.status === status) && matches([x.name, x.mobile, x.email, x.source, x.digitalMarketingAssigned?.name]));
  const showCreate = () => { setEditing(null); setUserForm(emptyUser); setUserModal(true); };
  const showEdit = (item) => { setEditing(item); setUserForm({ name: item.name, email: item.email, mobile: item.mobile || "", password: "", isActive: item.isActive }); setUserModal(true); };
  const saveUser = async (event) => { event.preventDefault(); try { await api(editing ? `/digital-marketing/admin/executives/${editing._id}` : "/digital-marketing/admin/executives", { method: editing ? "PATCH" : "POST", body: JSON.stringify(userForm) }); setUserModal(false); setMessage(editing ? "Executive updated" : "Executive created"); await load(); } catch (e) { setMessage(e.message); } };
  const removeUser = async (item) => { if (!window.confirm(`Delete ${item.name}?`)) return; try { await api(`/digital-marketing/admin/executives/${item._id}`, { method: "DELETE" }); setMessage("Executive deleted"); await load(); } catch (e) { setMessage(e.message); } };
  const toggleUser = async (item) => { try { await api(`/digital-marketing/admin/executives/${item._id}`, { method: "PATCH", body: JSON.stringify({ isActive: !item.isActive }) }); await load(); } catch (e) { setMessage(e.message); } };
  const assign = async (leadId, executiveId) => { if (!executiveId) return; try { await api(`/digital-marketing/admin/leads/${leadId}/assign`, { method: "PATCH", body: JSON.stringify({ executiveId }) }); setMessage("Lead assigned successfully"); await load(); } catch (e) { setMessage(e.message); } };
  const saveTask = async (event) => { event.preventDefault(); try { await api("/digital-marketing/admin/tasks", { method: "POST", body: JSON.stringify(taskForm) }); setTaskModal(false); setTaskForm(emptyTask); setMessage("Task assigned successfully"); await load(); } catch (e) { setMessage(e.message); } };

  return <div className="space-y-5">
    <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold">Digital Marketing Management</h2><p className="text-sm text-slate-500">Manage executives, assign leads, and monitor follow-ups, tasks and conversions.</p></div>{tab === "Executives" ? <button onClick={showCreate} className={primaryClass}><Plus size={16} /> Add Executive</button> : tab === "Tasks" ? <button onClick={() => setTaskModal(true)} className={primaryClass}><Plus size={16} /> Assign Task</button> : null}</div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Assigned Leads" value={totals.leads} /><MetricCard label="Converted Leads" value={totals.converted} /><MetricCard label="Pending Follow-ups" value={totals.followUps} /><MetricCard label="Marketing Tasks" value={totals.tasks} /></div>
    <div className="flex flex-wrap gap-2">{tabs.map((item) => <button key={item} onClick={() => { setTab(item); setStatus(""); }} className={`rounded-md px-4 py-2 text-sm font-semibold ${tab === item ? "bg-[#111315] text-white" : "border border-slate-200 bg-white"}`}>{item}</button>)}</div>
    <section className="flex flex-col gap-2 rounded-lg border border-slate-200 bg-white p-4 sm:flex-row"><input className={inputClass} placeholder="Search records" value={search} onChange={(e) => setSearch(e.target.value)} />{tab === "Executives" && <select className={inputClass} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All users</option><option>Active</option><option>Inactive</option></select>}{tab === "Leads" && <select className={inputClass} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{["New", "Contacted", "Interested", "Follow-up", "Converted", "Not Interested"].map((s) => <option key={s}>{s}</option>)}</select>}</section>
    {message && <p className="rounded-md border border-[#f97316]/20 bg-[#fff3e8] px-4 py-3 text-sm text-[#c2410c]">{message}</p>}
    {tab === "Executives" && <Table headers={["Name", "Email", "Mobile", "Status", "Leads", "Converted", "Pending Follow-ups", "Tasks", "Actions"]}>{filteredExecutives.map((x) => <Row key={x._id} values={[x.name, x.email, x.mobile, x.isActive ? "Active" : "Inactive", x.leadCount, x.convertedLeads, x.pendingFollowUps, x.taskCount]}><div className="flex gap-1"><button onClick={() => toggleUser(x)} className="rounded border px-2 py-1 text-xs">{x.isActive ? "Deactivate" : "Activate"}</button><IconButton onClick={() => showEdit(x)}><Pencil size={15} /></IconButton><IconButton onClick={() => removeUser(x)}><Trash2 size={15} /></IconButton></div></Row>)}</Table>}
    {tab === "Leads" && <Table headers={["Lead", "Mobile", "Email", "Course", "Source", "Status", "Executive", "Assign"]}>{filteredLeads.map((x) => <Row key={x._id} values={[x.name, x.mobile, x.email, x.courseInterested?.name, x.source, x.status, x.digitalMarketingAssigned?.name || "Unassigned"]}><select className="rounded-md border border-slate-200 px-2 py-1 text-xs" value={x.digitalMarketingAssigned?._id || ""} onChange={(e) => assign(x._id, e.target.value)}><option value="">Select executive</option>{activeExecutives.map((u) => <option key={u._id} value={u._id}>{u.name}</option>)}</select></Row>)}</Table>}
    {tab === "Follow-ups" && <Table headers={["Lead", "Executive", "Date", "Notes", "Status"]}>{followUps.filter((x) => matches([x.lead?.name, x.assignedTo?.name, x.status])).map((x) => <Row key={x._id} values={[x.lead?.name, x.assignedTo?.name, formatDate(x.dueAt), x.remarks, x.status]} />)}</Table>}
    {tab === "Tasks" && <Table headers={["Task", "Executive", "Description", "Due Date", "Priority", "Status"]}>{tasks.filter((x) => matches([x.title, x.assignedTo?.name, x.status])).map((x) => <Row key={x._id} values={[x.title, x.assignedTo?.name, x.description, formatDate(x.deadline), x.priority, x.status]} />)}</Table>}
    {userModal && <Modal title={editing ? "Edit Executive" : "Add Executive"} close={() => setUserModal(false)}><form onSubmit={saveUser} className="space-y-3"><input required className={inputClass} placeholder="Name" value={userForm.name} onChange={(e) => setUserForm({ ...userForm, name: e.target.value })} /><input required type="email" className={inputClass} placeholder="Email" value={userForm.email} onChange={(e) => setUserForm({ ...userForm, email: e.target.value })} /><input className={inputClass} placeholder="Mobile" value={userForm.mobile} onChange={(e) => setUserForm({ ...userForm, mobile: e.target.value })} /><input required={!editing} minLength="6" type="password" className={inputClass} placeholder={editing ? "New password (optional)" : "Password"} value={userForm.password} onChange={(e) => setUserForm({ ...userForm, password: e.target.value })} /><label className="flex gap-2 text-sm"><input type="checkbox" checked={userForm.isActive} onChange={(e) => setUserForm({ ...userForm, isActive: e.target.checked })} /> Active</label><button className={primaryClass}>{editing ? "Update" : "Create"}</button></form></Modal>}
    {taskModal && <Modal title="Assign Marketing Task" close={() => setTaskModal(false)}><form onSubmit={saveTask} className="space-y-3"><input required className={inputClass} placeholder="Task name" value={taskForm.title} onChange={(e) => setTaskForm({ ...taskForm, title: e.target.value })} /><textarea className={`${inputClass} min-h-20`} placeholder="Description" value={taskForm.description} onChange={(e) => setTaskForm({ ...taskForm, description: e.target.value })} /><input required type="date" className={inputClass} value={taskForm.dueDate} onChange={(e) => setTaskForm({ ...taskForm, dueDate: e.target.value })} /><select className={inputClass} value={taskForm.priority} onChange={(e) => setTaskForm({ ...taskForm, priority: e.target.value })}>{["Low", "Medium", "High", "Urgent"].map((x) => <option key={x}>{x}</option>)}</select><select required className={inputClass} value={taskForm.assignedTo} onChange={(e) => setTaskForm({ ...taskForm, assignedTo: e.target.value })}><option value="">Select executive</option>{activeExecutives.map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select><button className={primaryClass}>Assign Task</button></form></Modal>}
  </div>;
}

const inputClass = "w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#f97316]"; const primaryClass = "inline-flex items-center justify-center gap-2 rounded-md bg-[#f97316] px-4 py-2 text-sm font-semibold text-white hover:bg-[#111315]";
function Table({ headers, children }) { return <div className="table-wrap rounded-lg border border-slate-200 bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headers.map((h) => <th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Row({ values, children }) { return <tr className="border-b border-slate-100">{values.map((v, i) => <td key={i} className="px-3 py-3">{v ?? "-"}</td>)}{children && <td className="px-3 py-3">{children}</td>}</tr>; }
function IconButton({ onClick, children }) { return <button onClick={onClick} className="rounded-md border border-slate-200 p-1.5 text-[#ea580c]">{children}</button>; }
function Modal({ title, close, children }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-lg bg-white p-5"><div className="mb-4 flex justify-between"><h2 className="font-bold">{title}</h2><button onClick={close}><X size={18} /></button></div>{children}</div></div>; }
